version: '3.5'
services:
  imgpush:
    ports:
        - "5000:5000"
    build: .
    volumes:
      - ./app:/app
      - ./files:/files
      - ./cache:/cache
      - ./temporary:/temporary
    healthcheck:
      start_period: 0s
      test: ['CMD-SHELL', 'curl localhost:5000/liveness -s -f -o /dev/null || exit 1']
      interval: 30s
    environment:
      - S3_ENDPOINT=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
      - S3_BUCKET_NAME=

  metrics-rebuilder:
    build: .
    volumes:
      - ./app:/app
    environment:
      - REBUILD_METRICS=true
      - S3_ENDPOINT=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
      - S3_BUCKET_NAME=
