global:
  scrape_interval: 60s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["prometheus-alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "client1-prod"
    static_configs:
      - targets: ["imgpush-prod-client1:5000"]
        labels:
          environment: "prod"
          client: "Client 1"

    metrics_path: "/metrics"

  - job_name: "client1-staging"
    static_configs:
      - targets: ["172.17.0.1:55001"]
        labels:
          environment: "staging"
          client: "Client 1"

    metrics_path: "/metrics"

  - job_name: "client2-staging"
    static_configs:
      - targets: ["172.17.0.1:55002"]
        labels:
          environment: "staging"
          client: "Client 2"

  - job_name: "client2-prod"
    static_configs:
      - targets: ["172.17.0.1:55003"]
        labels:
          environment: "prod"
          client: "Client 2"

    metrics_path: "/metrics"
